// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplyProjectPatch(arg1, arg2, arg3) {
  return window['go']['main']['App']['ApplyProjectPatch'](arg1, arg2, arg3);
}

export function BootstrapScratchProject(arg1, arg2) {
  return window['go']['main']['App']['BootstrapScratchProject'](arg1, arg2);
}

export function CaptureProjectSource(arg1) {
  return window['go']['main']['App']['CaptureProjectSource'](arg1);
}

export function CreateScratchProject(arg1) {
  return window['go']['main']['App']['CreateScratchProject'](arg1);
}

export function GetModelConfig() {
  return window['go']['main']['App']['GetModelConfig']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ListLocalProjects() {
  return window['go']['main']['App']['ListLocalProjects']();
}

export function ProxyRequest(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['ProxyRequest'](arg1, arg2, arg3, arg4, arg5);
}

export function RegisterLocalProject() {
  return window['go']['main']['App']['RegisterLocalProject']();
}
