// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ApplyProjectPatch(arg1:string,arg2:string,arg3:string):Promise<main.PatchApplication>;

export function BootstrapScratchProject(arg1:string,arg2:string):Promise<main.ScratchProject>;

export function CaptureProjectSource(arg1:string):Promise<main.SourceArchive>;

export function CreateScratchProject(arg1:string):Promise<main.ScratchProject>;

export function GetModelConfig():Promise<main.RedactedModelConfig>;

export function Greet(arg1:string):Promise<string>;

export function ListLocalProjects():Promise<Array<main.ScratchProject>>;

export function ProxyRequest(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<main.ProxyResponse>;

export function RegisterLocalProject():Promise<main.ScratchProject>;
