// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {json} from '../models';

export function ApplyProjectMerge(arg1:string,arg2:string,arg3:string):Promise<main.GitState>;

export function ApplyProjectPatch(arg1:string,arg2:string,arg3:string):Promise<main.PatchApplication>;

export function BootstrapScratchProject(arg1:string,arg2:string):Promise<main.ScratchProject>;

export function CaptureProjectSource(arg1:string):Promise<main.SourceArchive>;

export function CreateScratchProject(arg1:string):Promise<main.ScratchProject>;

export function DiscardProjectMerge(arg1:string,arg2:string):Promise<void>;

export function GetModelConfig():Promise<main.RedactedModelConfig>;

export function GetProjectCommand(arg1:string):Promise<main.CommandState>;

export function GetProjectGit(arg1:string):Promise<main.GitState>;

export function GetProjectProtocol(arg1:string,arg2:string,arg3:number):Promise<main.ProtocolState>;

export function Greet(arg1:string):Promise<string>;

export function ListLocalProjects():Promise<Array<main.ScratchProject>>;

export function ListProjectFiles(arg1:string):Promise<Array<main.ProjectFile>>;

export function PreviewProjectMerge(arg1:string,arg2:string,arg3:string):Promise<main.MergePreview>;

export function ProjectBrowser(arg1:string,arg2:string,arg3:string,arg4:number,arg5:number):Promise<main.BrowserState>;

export function ProjectGitAction(arg1:string,arg2:string,arg3:string,arg4:string,arg5:Array<string>):Promise<main.GitState>;

export function ProjectProtocolRequest(arg1:string,arg2:string,arg3:string,arg4:string,arg5:boolean):Promise<json.RawMessage>;

export function ProxyRequest(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<main.ProxyResponse>;

export function ReadProjectFile(arg1:string,arg2:string):Promise<main.EditorFile>;

export function RegisterLocalProject():Promise<main.ScratchProject>;

export function ResolveProjectMerge(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<main.MergePreview>;

export function SaveProjectFile(arg1:string,arg2:string,arg3:string,arg4:string):Promise<main.EditorFile>;

export function StartProjectCommand(arg1:string,arg2:string,arg3:Array<string>):Promise<main.CommandState>;

export function StartProjectProtocol(arg1:string,arg2:string,arg3:string,arg4:Array<string>):Promise<main.ProtocolState>;

export function StopProjectCommand(arg1:string,arg2:string):Promise<void>;

export function StopProjectProtocol(arg1:string,arg2:string):Promise<void>;
