// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplyProjectMerge(arg1, arg2, arg3) {
  return window['go']['main']['App']['ApplyProjectMerge'](arg1, arg2, arg3);
}

export function ApplyProjectPatch(arg1, arg2, arg3) {
  return window['go']['main']['App']['ApplyProjectPatch'](arg1, arg2, arg3);
}

export function BootstrapScratchProject(arg1, arg2) {
  return window['go']['main']['App']['BootstrapScratchProject'](arg1, arg2);
}

export function CaptureProjectSource(arg1) {
  return window['go']['main']['App']['CaptureProjectSource'](arg1);
}

export function CreateScratchProject(arg1) {
  return window['go']['main']['App']['CreateScratchProject'](arg1);
}

export function DiscardProjectMerge(arg1, arg2) {
  return window['go']['main']['App']['DiscardProjectMerge'](arg1, arg2);
}

export function GetModelConfig() {
  return window['go']['main']['App']['GetModelConfig']();
}

export function GetProjectCommand(arg1) {
  return window['go']['main']['App']['GetProjectCommand'](arg1);
}

export function GetProjectGit(arg1) {
  return window['go']['main']['App']['GetProjectGit'](arg1);
}

export function GetProjectProtocol(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetProjectProtocol'](arg1, arg2, arg3);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ListLocalProjects() {
  return window['go']['main']['App']['ListLocalProjects']();
}

export function ListProjectFiles(arg1) {
  return window['go']['main']['App']['ListProjectFiles'](arg1);
}

export function PreviewProjectMerge(arg1, arg2, arg3) {
  return window['go']['main']['App']['PreviewProjectMerge'](arg1, arg2, arg3);
}

export function ProjectBrowser(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['ProjectBrowser'](arg1, arg2, arg3, arg4, arg5);
}

export function ProjectGitAction(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['ProjectGitAction'](arg1, arg2, arg3, arg4, arg5);
}

export function ProjectProtocolRequest(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['ProjectProtocolRequest'](arg1, arg2, arg3, arg4, arg5);
}

export function ProxyRequest(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['ProxyRequest'](arg1, arg2, arg3, arg4, arg5);
}

export function ReadProjectFile(arg1, arg2) {
  return window['go']['main']['App']['ReadProjectFile'](arg1, arg2);
}

export function RegisterLocalProject() {
  return window['go']['main']['App']['RegisterLocalProject']();
}

export function ResolveProjectMerge(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['ResolveProjectMerge'](arg1, arg2, arg3, arg4, arg5);
}

export function SaveProjectFile(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SaveProjectFile'](arg1, arg2, arg3, arg4);
}

export function StartProjectCommand(arg1, arg2, arg3) {
  return window['go']['main']['App']['StartProjectCommand'](arg1, arg2, arg3);
}

export function StartProjectProtocol(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['StartProjectProtocol'](arg1, arg2, arg3, arg4);
}

export function StopProjectCommand(arg1, arg2) {
  return window['go']['main']['App']['StopProjectCommand'](arg1, arg2);
}

export function StopProjectProtocol(arg1, arg2) {
  return window['go']['main']['App']['StopProjectProtocol'](arg1, arg2);
}
