// Package decision provides a small client for the Kev/Jev SystemOne
// decision endpoint. It deliberately only handles a fixed choice question;
// planning and tool argument generation remain the caller's responsibility.
package decision

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"math"
	"net/http"
	"net/url"
	"strings"
	"time"
)

const (
	// DefaultBaseURL is the address used by the local Kev/Jev sidecar when a
	// Client has no BaseURL configured.
	DefaultBaseURL = "http://127.0.0.1:8009"

	// DefaultModel is the model selected by the local sidecar when no model is
	// included in a SystemOne request.
	DefaultModel = "kev-latest"

	// DeferChoice is always included in a choice request. It gives a caller a
	// way to hand a low-confidence decision back to its normal planner.
	DeferChoice = "defer"

	defaultTimeout    = 10 * time.Second
	maxResponseBytes  = 4 << 20
	maxErrorBodyBytes = 32 << 10
	maxOptions        = 255
	questionID        = "next_tool"
)

// Option is one fixed action the decision model may select. Name is returned
// in ChoiceResult.Probabilities and as Choice; Description is shown to the
// decision model and is not generated by the model.
type Option struct {
	Name        string
	Description string
}

// ChoiceResult is the validated decision returned by SystemOne.
type ChoiceResult struct {
	Choice        string
	Confidence    float64
	Probabilities map[string]float64
	Model         string
	LatencyMS     float64
}

// Client calls the Kev/Jev SystemOne HTTP endpoint. BaseURL accepts a host
// (http://127.0.0.1:8009), a /v1 URL, or the complete /v1/systemone URL.
// APIKey is sent as a bearer token when non-empty. HTTP can be supplied to
// customize transport behavior; a nil HTTP uses http.DefaultClient.
//
// Timeout is an optional per-call upper bound. A zero value uses ten seconds;
// a caller's earlier context deadline still wins.
type Client struct {
	BaseURL string
	APIKey  string
	HTTP    *http.Client
	Model   string
	Timeout time.Duration
}

// Choose asks SystemOne to select one of options, plus the mandatory defer
// choice. It returns an error for network failures, non-2xx responses, invalid
// JSON, or a response that does not describe exactly the requested candidates.
// The caller should treat such an error as fail-open and continue with its
// existing planner or policy.
func (c Client) Choose(ctx context.Context, state string, options []Option) (ChoiceResult, error) {
	if ctx == nil {
		ctx = context.Background()
	}
	candidates, err := normalizeOptions(options)
	if err != nil {
		return ChoiceResult{}, err
	}

	endpoint, err := c.endpoint()
	if err != nil {
		return ChoiceResult{}, err
	}

	request := systemOneRequest{
		State: state,
		Questions: map[string]question{
			questionID: {
				Type:         "choice",
				Instructions: "Choose the next action from the supplied options. Select defer when no option is clearly appropriate.",
				Criteria:     optionCriteria(candidates),
			},
		},
	}
	if model := strings.TrimSpace(c.Model); model != "" {
		request.Model = model
	}
	body, err := json.Marshal(request)
	if err != nil {
		return ChoiceResult{}, fmt.Errorf("encode SystemOne request: %w", err)
	}

	timeout := c.Timeout
	if timeout <= 0 {
		timeout = defaultTimeout
	}
	callCtx, cancel := context.WithTimeout(ctx, timeout)
	defer cancel()
	req, err := http.NewRequestWithContext(callCtx, http.MethodPost, endpoint, bytes.NewReader(body))
	if err != nil {
		return ChoiceResult{}, fmt.Errorf("create SystemOne request: %w", err)
	}
	req.Header.Set("Content-Type", "application/json")
	req.Header.Set("Accept", "application/json")
	if strings.TrimSpace(c.APIKey) != "" {
		req.Header.Set("Authorization", "Bearer "+strings.TrimSpace(c.APIKey))
	}
	httpClient := c.HTTP
	if httpClient == nil {
		httpClient = http.DefaultClient
	}
	resp, err := httpClient.Do(req)
	if err != nil {
		return ChoiceResult{}, fmt.Errorf("SystemOne request: %w", err)
	}
	defer resp.Body.Close()
	if resp.StatusCode < http.StatusOK || resp.StatusCode >= http.StatusMultipleChoices {
		message, readErr := io.ReadAll(io.LimitReader(resp.Body, maxErrorBodyBytes))
		if readErr != nil {
			return ChoiceResult{}, fmt.Errorf("SystemOne returned %s (read error: %w)", resp.Status, readErr)
		}
		if text := strings.TrimSpace(string(message)); text != "" {
			return ChoiceResult{}, fmt.Errorf("SystemOne returned %s: %s", resp.Status, text)
		}
		return ChoiceResult{}, fmt.Errorf("SystemOne returned %s", resp.Status)
	}
	responseBody, err := io.ReadAll(io.LimitReader(resp.Body, maxResponseBytes+1))
	if err != nil {
		return ChoiceResult{}, fmt.Errorf("read SystemOne response: %w", err)
	}
	if len(responseBody) > maxResponseBytes {
		return ChoiceResult{}, fmt.Errorf("SystemOne response exceeds %d bytes", maxResponseBytes)
	}
	var response systemOneResponse
	if err := json.Unmarshal(responseBody, &response); err != nil {
		return ChoiceResult{}, fmt.Errorf("decode SystemOne response: %w", err)
	}
	return validateResponse(response, candidates)
}

func (c Client) endpoint() (string, error) {
	base := strings.TrimSpace(c.BaseURL)
	if base == "" {
		base = DefaultBaseURL
	}
	parsed, err := url.Parse(base)
	if err != nil || parsed.Scheme == "" || parsed.Host == "" {
		return "", fmt.Errorf("invalid decision BaseURL %q", base)
	}
	path := strings.TrimRight(parsed.Path, "/")
	switch {
	case strings.HasSuffix(path, "/v1/systemone"):
		parsed.Path = path
	case strings.HasSuffix(path, "/v1"):
		parsed.Path = path + "/systemone"
	default:
		parsed.Path = path + "/v1/systemone"
	}
	return parsed.String(), nil
}

func normalizeOptions(options []Option) ([]Option, error) {
	if len(options) > maxOptions {
		return nil, fmt.Errorf("decision options exceed %d", maxOptions)
	}
	seen := make(map[string]struct{}, len(options)+1)
	out := make([]Option, 0, len(options)+1)
	for _, option := range options {
		name := strings.TrimSpace(option.Name)
		if name == "" {
			return nil, errors.New("decision option name is empty")
		}
		if _, ok := seen[name]; ok {
			return nil, fmt.Errorf("duplicate decision option %q", name)
		}
		seen[name] = struct{}{}
		option.Name = name
		out = append(out, option)
	}
	if _, ok := seen[DeferChoice]; !ok {
		if len(out) >= maxOptions {
			return nil, fmt.Errorf("decision options plus %q exceed %d", DeferChoice, maxOptions)
		}
		out = append(out, Option{Name: DeferChoice, Description: "Defer the decision to the normal planner."})
	}
	return out, nil
}

func optionCriteria(options []Option) map[string]string {
	criteria := make(map[string]string, len(options))
	for _, option := range options {
		criteria[option.Name] = option.Description
	}
	return criteria
}

func validateResponse(response systemOneResponse, candidates []Option) (ChoiceResult, error) {
	answer, ok := response.Answers[questionID]
	if !ok {
		return ChoiceResult{}, fmt.Errorf("SystemOne response is missing answer %q", questionID)
	}
	if answer.Type != "choice" {
		return ChoiceResult{}, fmt.Errorf("SystemOne answer %q has type %q, want choice", questionID, answer.Type)
	}
	if answer.Choice == "" {
		return ChoiceResult{}, fmt.Errorf("SystemOne answer %q has no choice", questionID)
	}
	allowed := make(map[string]struct{}, len(candidates))
	for _, option := range candidates {
		allowed[option.Name] = struct{}{}
	}
	if _, ok := allowed[answer.Choice]; !ok {
		return ChoiceResult{}, fmt.Errorf("SystemOne selected unknown choice %q", answer.Choice)
	}
	if !finiteUnit(answer.Confidence) {
		return ChoiceResult{}, fmt.Errorf("SystemOne confidence is not a finite number in [0,1]: %v", answer.Confidence)
	}
	if len(answer.Probabilities) != len(candidates) {
		return ChoiceResult{}, fmt.Errorf("SystemOne returned %d probabilities for %d choices", len(answer.Probabilities), len(candidates))
	}
	sum := 0.0
	for _, option := range candidates {
		probability, ok := answer.Probabilities[option.Name]
		if !ok {
			return ChoiceResult{}, fmt.Errorf("SystemOne probabilities are missing choice %q", option.Name)
		}
		if !finiteUnit(probability) {
			return ChoiceResult{}, fmt.Errorf("SystemOne probability for %q is not a finite number in [0,1]: %v", option.Name, probability)
		}
		sum += probability
	}
	for name := range answer.Probabilities {
		if _, ok := allowed[name]; !ok {
			return ChoiceResult{}, fmt.Errorf("SystemOne probabilities contain unknown choice %q", name)
		}
	}
	// Kev rounds distributions to four decimals. Its documented maximum
	// rounding error is below .02 even at the 255-option limit.
	if math.Abs(sum-1) > 0.05 {
		return ChoiceResult{}, fmt.Errorf("SystemOne probabilities sum to %v, want approximately 1", sum)
	}
	probabilities := make(map[string]float64, len(answer.Probabilities))
	for name, probability := range answer.Probabilities {
		probabilities[name] = probability
	}
	return ChoiceResult{
		Choice:        answer.Choice,
		Confidence:    answer.Confidence,
		Probabilities: probabilities,
		Model:         response.Model,
		LatencyMS:     response.LatencyMS,
	}, nil
}

func finiteUnit(value float64) bool {
	return !math.IsNaN(value) && !math.IsInf(value, 0) && value >= 0 && value <= 1
}

type systemOneRequest struct {
	State     string              `json:"state"`
	Model     string              `json:"model,omitempty"`
	Questions map[string]question `json:"questions"`
}

type question struct {
	Type         string            `json:"type"`
	Instructions string            `json:"instructions"`
	Criteria     map[string]string `json:"criteria"`
}

type systemOneResponse struct {
	Model     string                  `json:"model"`
	Answers   map[string]choiceAnswer `json:"answers"`
	LatencyMS float64                 `json:"latency_ms"`
}

type choiceAnswer struct {
	Type          string             `json:"type"`
	Choice        string             `json:"choice"`
	Confidence    float64            `json:"confidence"`
	Probabilities map[string]float64 `json:"probabilities"`
}
