import { useState } from "react";
import { desktopApp } from "./api";
import type { GitState, MergePreview, Project } from "./types";

export function MergeWorkbench({project,state,blocked,onApplied}:{project:Project;state:GitState;blocked:boolean;onApplied:(state:GitState)=>void}) {
  const [target,setTarget]=useState("origin/main"),[preview,setPreview]=useState<MergePreview|null>(null);
  const [busy,setBusy]=useState(false),[error,setError]=useState(""),[selected,setSelected]=useState(""),[draft,setDraft]=useState("");
  const run=async(action:()=>Promise<void>)=>{if(busy||blocked)return;setBusy(true);setError("");try{await action();}catch(cause){setError(String(cause));}finally{setBusy(false);}};
  const create=()=>run(async()=>{if(preview){await desktopApp()!.DiscardProjectMerge!(project.localHandle!,preview.id);setPreview(null);}const next=await desktopApp()!.PreviewProjectMerge!(project.localHandle!,state.revision,target);setPreview(next);setSelected(next.files[0]?.path||"");setDraft(next.files[0]?.result||"");});
  const file=preview?.files.find(value=>value.path===selected);
  return <section className="merge-workbench"><h2>结构化合并</h2><p>Git 三方合并 → Mergiraf 语法树 → 人工审查。确定性路径不调用模型。</p>
    <form onSubmit={event=>{event.preventDefault();void create();}}><input aria-label="合并目标" value={target} onChange={event=>setTarget(event.target.value)} placeholder="origin/main / feature/orders"/><button className="secondary-button" disabled={busy||blocked||state.files.length>0||!target.trim()||!desktopApp()?.PreviewProjectMerge}>隔离预览</button></form>
    {state.files.length>0&&<small>先提交当前修改，保留两个分支的完整历史。</small>}{error&&<div className="data-error" role="alert">{error}</div>}
    {preview&&<><div className="merge-summary"><strong>{preview.engine}</strong><small>{preview.ours.slice(0,8)} + {preview.theirs.slice(0,8)} · base {preview.base.slice(0,8)}</small><p>{preview.files.length===0?"Git 已自动合并，无需模型。":`原始冲突 ${preview.files.length} 个，已解决 ${preview.files.filter(value=>value.resolved).length} 个。`}</p><p>语法兼容仍需业务测试。临时工程：<code>{preview.path}</code>；可在该目录运行测试，修改后需重新预览。</p></div>
      {preview.files.length>0&&<><select aria-label="冲突文件" value={selected} disabled={busy} onChange={event=>{const next=preview.files.find(value=>value.path===event.target.value)!;setSelected(next.path);setDraft(next.result);}}>{preview.files.map(value=><option key={value.path} value={value.path}>{value.resolved?"✓":"!"} {value.path} · {value.method}</option>)}</select>{file&&<><div className="merge-three-way">{([['共同祖先',file.base],['我的修改',file.ours],['同事修改',file.theirs]] as const).map(([title,content])=><details key={title}><summary>{title}</summary><pre>{content||"（缺失或无法作为文本显示）"}</pre></details>)}</div><label>合并结果<textarea aria-label="合并结果" rows={12} disabled={!file.editable||busy} value={draft} onChange={event=>setDraft(event.target.value)}/></label><button className="secondary-button" disabled={!file.editable||busy} onClick={()=>void run(async()=>{setPreview(await desktopApp()!.ResolveProjectMerge!(project.localHandle!,preview.id,preview.revision,file.path,draft));})}>保存此文件的解决方案</button>{!file.editable&&<p>二进制、删除、重命名或模式冲突需要外部处理。</p>}</>}</>}
      <details><summary>完整合并差异</summary><pre className="review-patch">{preview.patch||"无内容差异；合并仍会保留双方提交历史。"}</pre></details><div className="merge-actions"><button className="primary-button" disabled={busy||!preview.ready||!!file&&draft!==file.result} onClick={()=>{if(!window.confirm("批准将已审查的合并结果应用到当前分支？请确认业务测试通过。"))return;void run(async()=>{const next=await desktopApp()!.ApplyProjectMerge!(project.localHandle!,preview.id,preview.revision);onApplied(next);setPreview(null);});}}>批准应用合并</button><button className="secondary-button" disabled={busy} onClick={()=>void run(async()=>{await desktopApp()!.DiscardProjectMerge!(project.localHandle!,preview.id);setPreview(null);})}>丢弃预览</button></div><small>批准前不修改原工程的文件、索引与分支。批准后保留 refs/proofcode/backups 中的原提交及本机审计记录。</small></>}
  </section>;
}
