import { createContext, useEffect, useRef, useState } from "react";
import { desktopApp } from "./api";
import type { Project, ProtocolState } from "./types";

export type LanguageSession={id:string;rootUri:string;language:string;handle:string;syncKind:number;openClose:boolean};
export type Breakpoints=Record<string,number[]>;
export const IDEProtocolContext=createContext<{session:LanguageSession|null;breakpoints:Breakpoints;line?:number;toggleBreakpoint:(path:string,line:number)=>void;onNavigate:(path:string,line?:number)=>void}>({session:null,breakpoints:{},toggleBreakpoint:()=>{},onNavigate:()=>{}});
export async function protocolRequest(handle:string,id:string,method:string,params:unknown,notification=false):Promise<any> {
  const response:any=await desktopApp()!.ProjectProtocolRequest!(handle,id,method,JSON.stringify(params),notification);
  if(notification)return null;
  if(response?.error)throw new Error(response.error.message||JSON.stringify(response.error));
  if(response?.success===false)throw new Error(response.message||"调试请求失败");
  return response?.result??response?.body??null;
}
function AdapterForm({program,args,setProgram,setArgs,busy,onStart,onStop,running}:{program:string;args:string;setProgram:(v:string)=>void;setArgs:(v:string)=>void;busy:boolean;onStart:()=>void;onStop:()=>void;running:boolean}) {
  return <form className="protocol-form" onSubmit={event=>{event.preventDefault();onStart();}}><label>服务程序<input aria-label="协议服务程序" disabled={running} value={program} onChange={event=>setProgram(event.target.value)}/></label><label>参数（JSON）<input aria-label="协议服务参数" disabled={running} value={args} onChange={event=>setArgs(event.target.value)}/></label><button className="secondary-button" disabled={busy||running||!program}>启动</button><button type="button" className="secondary-button" disabled={busy||!running} onClick={onStop}>停止</button></form>;
}
function parseArgs(value:string) {const parsed:unknown=JSON.parse(value);if(!Array.isArray(parsed)||parsed.some(v=>typeof v!=="string"))throw new Error("参数必须是字符串 JSON 数组");return parsed as string[];}
export function LanguageTools({project,onSession}:{project:Project;onSession:(session:LanguageSession|null)=>void}) {
  const [program,setProgram]=useState("pylsp"),[args,setArgs]=useState("[]"),[language,setLanguage]=useState("python"),[state,setState]=useState<ProtocolState|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(""),[capabilities,setCapabilities]=useState<any>(null);
  const live=useRef(true),current=useRef<ProtocolState|null>(null);
  useEffect(()=>{live.current=true;return()=>{live.current=false;const value=current.current;if(value)void desktopApp()?.StopProjectProtocol?.(project.localHandle!,value.id);};},[project.id]);
  const stop=async()=>{if(current.current)await desktopApp()!.StopProjectProtocol!(project.localHandle!,current.current.id);current.current=null;if(live.current){onSession(null);setState(null);}};
  const start=async()=>{setBusy(true);setError("");let session:ProtocolState|null=null;try{session=await desktopApp()!.StartProjectProtocol!(project.localHandle!,"lsp",program,parseArgs(args));if(!live.current){await desktopApp()!.StopProjectProtocol!(project.localHandle!,session.id);return;}current.current=session;const result=await protocolRequest(project.localHandle!,session.id,"initialize",{processId:null,rootUri:session.rootUri,workspaceFolders:[{uri:session.rootUri,name:project.name}],capabilities:{textDocument:{synchronization:{didSave:false},completion:{completionItem:{snippetSupport:false}},hover:{contentFormat:["plaintext","markdown"]}},workspace:{configuration:true}},clientInfo:{name:"ProofCode",version:"0.5.0"}});await protocolRequest(project.localHandle!,session.id,"initialized",{},true);if(live.current){const sync=result.capabilities?.textDocumentSync;setCapabilities(result.capabilities);setState(session);onSession({id:session.id,rootUri:session.rootUri,language,handle:project.localHandle!,syncKind:typeof sync==="number"?sync:sync?.change??0,openClose:typeof sync==="number"?sync!==0:!!sync?.openClose});}else await desktopApp()!.StopProjectProtocol!(project.localHandle!,session.id);}catch(cause){if(session)await desktopApp()!.StopProjectProtocol!(project.localHandle!,session.id);current.current=null;if(live.current)setError(String(cause));}finally{if(live.current)setBusy(false);}};
  return <section className="protocol-panel"><h2>语言服务 · LSP</h2><p>连接本机 stdio 语言服务器；补全、悬停、F12 定义与诊断进入编辑器。不同语言需安装对应服务器。</p><label>语言 ID <input disabled={!!state} value={language} onChange={event=>setLanguage(event.target.value)} placeholder="python / go / typescript"/></label><AdapterForm program={program} args={args} setProgram={setProgram} setArgs={setArgs} busy={busy} running={!!state} onStart={()=>void start()} onStop={()=>void stop().catch(cause=>setError(String(cause)))}/>{error&&<p role="alert" className="data-error">{error}</p>}{state&&<details><summary>服务已连接 · 能力协商结果</summary><pre>{JSON.stringify(capabilities,null,2)}</pre></details>}</section>;
}
export function DebugTools({project,path,breakpoints,onNavigate}:{project:Project;path?:string;breakpoints:Breakpoints;onNavigate:(path:string,line?:number)=>void}) {
  const [program,setProgram]=useState("python"),[args,setArgs]=useState('["-m","debugpy.adapter"]'),[launch,setLaunch]=useState('{"type":"python","request":"launch","name":"ProofCode","program":"main.py","console":"internalConsole","stopOnEntry":true}');
  const [state,setState]=useState<ProtocolState|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(""),[events,setEvents]=useState<any[]>([]),[frames,setFrames]=useState<any[]>([]),[variables,setVariables]=useState<any[]>([]),[scopes,setScopes]=useState<any[]>([]),[thread,setThread]=useState(0),[expression,setExpression]=useState("");
  const cursor=useRef(0),live=useRef(true),stateRef=useRef<ProtocolState|null>(null),frameRef=useRef(0),initialized=useRef(false),pointsRef=useRef(breakpoints);pointsRef.current=breakpoints;
  useEffect(()=>{live.current=true;return()=>{live.current=false;const value=stateRef.current;stateRef.current=null;if(value)void desktopApp()?.StopProjectProtocol?.(project.localHandle!,value.id).catch(()=>{});};},[project.id]);
  const request=async(method:string,params:unknown={})=>{const value=stateRef.current;if(!value)throw new Error("先启动调试器");return protocolRequest(project.localHandle!,value.id,method,params);};
  const perform=async(action:()=>Promise<void>)=>{if(busy||!live.current)return;setBusy(true);setError("");try{await action();}catch(cause){if(live.current)setError(String(cause));}finally{if(live.current)setBusy(false);}};
  const loadFrames=async(threadId:number)=>{const id=stateRef.current?.id;const result=await request("stackTrace",{threadId,startFrame:0,levels:30});if(live.current&&stateRef.current?.id===id)setFrames(result.stackFrames||[]);};
  useEffect(()=>{if(!state)return;let active=true,inFlight=false;const valid=()=>active&&live.current&&stateRef.current?.id===state.id;const tick=async()=>{if(inFlight||!valid())return;inFlight=true;try{const next=await desktopApp()!.GetProjectProtocol!(project.localHandle!,state.id,cursor.current);if(!valid())return;cursor.current=next.sequence;if(next.dropped)setError("调试事件超过保留上限，部分旧事件已丢弃");stateRef.current=next;setState(next);if(next.events.length)setEvents(old=>[...old,...next.events.map(v=>v.message)].slice(-100));for(const event of next.events){if(!valid())return;const msg=event.message;if(msg.event==="initialized")initialized.current=true;if(msg.event==="stopped"){const id=msg.body?.threadId||(await request("threads")).threads?.[0]?.id;if(id&&valid()){setThread(id);await loadFrames(id);}}if(valid()&&(msg.event==="continued"||msg.event==="terminated")){frameRef.current=0;setThread(0);setFrames([]);setScopes([]);setVariables([]);}}}catch(cause){if(valid())setError(String(cause));}finally{inFlight=false;}};void tick();const timer=setInterval(()=>void tick(),600);return()=>{active=false;clearInterval(timer);};},[state?.id]);
  const sourcePath=(file:string)=>{const root=decodeURIComponent(new URL(stateRef.current!.rootUri).pathname).replace(/^\/([A-Za-z]:)/,"$1").replace(/\/$/,"");return `${root}/${file}`;};
  const setPoints=async(file:string)=>request("setBreakpoints",{source:{path:sourcePath(file)},breakpoints:(pointsRef.current[file]||[]).map(line=>({line})),sourceModified:false});
  useEffect(()=>{if(!state||!initialized.current)return;let active=true;for(const file of Object.keys(breakpoints))void setPoints(file).catch(cause=>{if(active&&live.current)setError(String(cause));});return()=>{active=false;};},[breakpoints,state?.id]);
  const start=()=>perform(async()=>{cursor.current=0;initialized.current=false;frameRef.current=0;setEvents([]);setFrames([]);setScopes([]);setVariables([]);setThread(0);const next=await desktopApp()!.StartProjectProtocol!(project.localHandle!,"dap",program,parseArgs(args));if(!live.current){await desktopApp()!.StopProjectProtocol!(project.localHandle!,next.id);return;}stateRef.current=next;setState(next);try{await request("initialize",{clientID:"proofcode",adapterID:"configured",linesStartAt1:true,columnsStartAt1:true,pathFormat:"path",supportsVariableType:true,supportsRunInTerminalRequest:false});}catch(cause){await desktopApp()!.StopProjectProtocol!(project.localHandle!,next.id);stateRef.current=null;if(live.current)setState(null);throw cause;}});
  const launchProgram=()=>perform(async()=>{const config=JSON.parse(launch);if(config.program&&!/^(?:[a-zA-Z]:[\\/]|\/)/.test(config.program))config.program=sourcePath(config.program);if(!config.cwd)config.cwd=sourcePath("");const launching=request(config.request==="attach"?"attach":"launch",config);let launchError:unknown=null;void launching.catch(cause=>{launchError=cause;});const deadline=Date.now()+12000;while(live.current&&stateRef.current&&!initialized.current&&Date.now()<deadline&&!launchError)await new Promise(resolve=>setTimeout(resolve,100));if(!live.current||!stateRef.current)return;if(launchError)throw launchError;if(!initialized.current)throw new Error("适配器未发出 initialized 事件");for(const file of Object.keys(pointsRef.current))await setPoints(file);await request("configurationDone",{});await launching;});
  const chooseFrame=(frame:any)=>perform(async()=>{const id=stateRef.current?.id;frameRef.current=frame.id;const result=await request("scopes",{frameId:frame.id});if(!live.current||stateRef.current?.id!==id||frameRef.current!==frame.id)return;setScopes(result.scopes||[]);setVariables([]);if(frame.source?.path){const root=sourcePath("");const file=String(frame.source.path).split("\\").join("/");if(file.toLowerCase().startsWith(root.toLowerCase()))onNavigate(file.slice(root.length),frame.line);}});
  const stop=()=>perform(async()=>{const value=stateRef.current;if(!value)return;stateRef.current=null;frameRef.current=0;initialized.current=false;try{await protocolRequest(project.localHandle!,value.id,"disconnect",{terminateDebuggee:true});}finally{await desktopApp()!.StopProjectProtocol!(project.localHandle!,value.id);if(live.current){setState(null);setThread(0);setFrames([]);setScopes([]);setVariables([]);}}});
  const inspectScope=(scope:any)=>perform(async()=>{const id=stateRef.current?.id,frame=frameRef.current;const result=await request("variables",{variablesReference:scope.variablesReference});if(live.current&&stateRef.current?.id===id&&frameRef.current===frame)setVariables(result.variables||[]);});
  const evaluate=()=>perform(async()=>{const id=stateRef.current?.id,frame=frameRef.current;const result=await request("evaluate",{expression,frameId:frame,context:"repl"});if(live.current&&stateRef.current?.id===id&&frameRef.current===frame)setEvents(old=>[...old,{event:"evaluate",body:result}].slice(-100));});
  return <section className="protocol-panel"><h2>断点调试 · DAP</h2><p>点击编辑器行号左侧设置断点；使用 stdio 调试适配器，启动程序、查看堆栈和变量、继续或单步运行。</p><AdapterForm program={program} args={args} setProgram={setProgram} setArgs={setArgs} busy={busy} running={!!state?.running} onStart={()=>void start()} onStop={()=>void stop()}/><label>启动／附加配置（DAP JSON）<textarea aria-label="调试启动配置" rows={4} value={launch} onChange={event=>setLaunch(event.target.value)}/></label><div className="debug-actions"><button className="primary-button" disabled={!state?.running||busy} onClick={()=>void launchProgram()}>启动调试程序</button>{["continue","next","stepIn","stepOut","pause"].map((command,i)=><button className="secondary-button" key={command} disabled={!state?.running||busy||command!=="pause"&&!thread} onClick={()=>void perform(async()=>{await request(command,{threadId:thread||1});})}>{["继续","步过","步入","步出","暂停"][i]}</button>)}</div>{error&&<p role="alert" className="data-error">{error}</p>}<small>当前文件 {path||"未选择"} · 断点 {Object.values(breakpoints).flat().length} · {state?.running?thread?"已暂停":"调试器运行中":"已停止"}</small><div className="debug-inspection"><div><h3>调用堆栈</h3>{frames.map(frame=><button className="text-button" key={frame.id} onClick={()=>void chooseFrame(frame)}>{frame.name} · {frame.line}</button>)}</div><div><h3>作用域</h3>{scopes.map(scope=><button className="text-button" key={scope.variablesReference} onClick={()=>void inspectScope(scope)}>{scope.name}</button>)}<pre>{variables.map(v=>`${v.name}: ${v.value}`).join("\n")}</pre></div></div><form onSubmit={event=>{event.preventDefault();void evaluate();}}><input aria-label="调试表达式" value={expression} onChange={event=>setExpression(event.target.value)} placeholder="调试表达式（可能产生副作用）"/><button className="secondary-button" disabled={!thread||busy}>求值</button></form><details><summary>调试输出与事件</summary><pre>{events.map(event=>event.event==="output"?event.body?.output:JSON.stringify(event)).join("\n")}{state?.error&&`\n${state.error}`}</pre></details></section>;
}
