import { useState } from "react";
import { GitBranch, KeyRound, Minus, Plus, Search, Table2 } from "lucide-react";
import type { TableMetadata } from "./dataModel";
import { tableKey } from "./dataModel";

export function SchemaDiagram({ tables, onChoose }: { tables: TableMetadata[]; onChoose: (table: TableMetadata) => void }) {
  const [filter, setFilter] = useState(""), [scale, setScale] = useState(1);
  const visible = tables.filter(table => tableKey(table).toLowerCase().includes(filter.toLowerCase())).slice(0, 30);
  const positions = new Map(visible.map((table, index) => [tableKey(table), { x: 32 + index % 3 * 310, y: 32 + Math.floor(index / 3) * 318 }]));
  const width = 964, height = Math.max(330, Math.ceil(visible.length / 3) * 318 + 32);
  const relationships = visible.flatMap(table => table.foreignKeys.map(key => ({ from: tableKey(table), to: `${key.referencesSchema}.${key.referencesTable}`, key })));
  return <section className="schema-diagram"><div className="data-panel-heading"><div><h2>表关系图</h2><p>连线来自数据库外键；点击表卡片可进入查询画布。</p></div><div className="diagram-tools"><button className="icon-button" aria-label="缩小关系图" onClick={() => setScale(value => Math.max(.5, value - .1))}><Minus size={16}/></button><span>{Math.round(scale * 100)}%</span><button className="icon-button" aria-label="放大关系图" onClick={() => setScale(value => Math.min(1.5, value + .1))}><Plus size={16}/></button></div></div><label className="diagram-search"><Search size={15}/><input aria-label="搜索关系图中的表" value={filter} onChange={event => setFilter(event.target.value)} placeholder="搜索表名或 schema"/></label>
    <div className="diagram-scroll"><div style={{ width: width * scale, height: height * scale }}><div className="diagram-world" style={{ width, height, transform: `scale(${scale})` }}><svg className="diagram-edges" viewBox={`0 0 ${width} ${height}`} role="img" aria-label={`${relationships.filter(edge => positions.has(edge.to)).length} 条已显示的外键关系`}><defs><marker id="schema-arrow" markerWidth="8" markerHeight="8" refX="7" refY="4" orient="auto"><path d="M 0 0 L 8 4 L 0 8" fill="#8da4b4"/></marker></defs>{relationships.map((edge, index) => { const from = positions.get(edge.from), to = positions.get(edge.to); if (!from || !to) return null; const forward = to.x > from.x; const x1 = from.x + (forward ? 262 : 0), y1 = from.y + 68, x2 = to.x + (forward ? 0 : 262), y2 = to.y + 68; const self = edge.from === edge.to; return <path key={`${edge.from}-${edge.key.name}`} d={self ? `M ${x1} ${y1} C ${x1 + 35} ${y1 - 85}, ${x2 - 26} ${y2 - 85}, ${x2} ${y2}` : `M ${x1} ${y1} C ${x1 + 25 + index % 3 * 12} ${y1}, ${x2 - 35} ${y2}, ${x2} ${y2}`} stroke="#8da4b4" strokeWidth="1.5" fill="none" markerEnd="url(#schema-arrow)"><title>{edge.from} ({edge.key.columns.join(", ")}) → {edge.to} ({edge.key.referencesColumns.join(", ")})</title></path>; })}</svg>
      {visible.map(table => { const point = positions.get(tableKey(table))!; return <article className="diagram-table" style={{ left: point.x, top: point.y }} key={tableKey(table)}><button className="diagram-table-title" onClick={() => onChoose(table)}><Table2 size={17}/><span><small>{table.schema}</small><strong>{table.name}</strong></span><span className="diagram-count">{table.columns.length}</span></button><div className="diagram-table-columns">{table.columns.slice(0, 6).map(column => <div key={column.name} title={column.comment}><span className="diagram-column-icon">{table.primaryKey.includes(column.name) ? <KeyRound size={12}/> : table.foreignKeys.some(key => key.columns.includes(column.name)) ? <GitBranch size={12}/> : <i/>}</span><span>{column.name}</span><small>{column.type}</small></div>)}{table.columns.length > 6 && <small className="diagram-more">另外 {table.columns.length - 6} 个字段</small>}</div><button className="diagram-query" onClick={() => onChoose(table)}>查看字段与构建查询 →</button></article>; })}
    </div></div>{!visible.length && <div className="empty-state">没有匹配的表</div>}</div><div className="diagram-legend"><span><KeyRound size={12}/>主键</span><span><GitBranch size={12}/>外键</span><span>{tables.length > 30 ? "每次最多显示 30 张表，可搜索定位" : `${visible.length} 张表`}</span><span>仅浏览结构，不执行查询</span></div>
  </section>;
}
